# This is the configuration used to check the rubocop source code.

inherit_from: .rubocop_todo.yml

AllCops:
  Exclude:
    - 'vendor/**/*'
    - 'spec/fixtures/**/*'
    - 'tmp/**/*'
  TargetRubyVersion: 2.0

Style/Encoding:
  EnforcedStyle: never
  Enabled: true

Style/FrozenStringLiteralComment:
  EnforcedStyle: always

Style/IndentHeredoc:
  EnforcedStyle: powerpack

Metrics/BlockLength:
  Exclude:
    - 'Rakefile'
    - '**/*.rake'
    - 'spec/**/*.rb'

AmbiguousBlockAssociation:
  Exclude:
    - 'spec/**/*.rb'
